name: Deploy DeepCheck to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build React frontend inside GitHub Actions
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build React frontend
        working-directory: Frontend/ai-image-detector
        run: |
          npm install
          npm run build

      # Copy dist folder to EC2
      - name: Upload frontend build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "Frontend/ai-image-detector/dist/*"
          target: "/home/ubuntu/deepcheck-frontend"
          strip_components: 2
          rm: true

      # Deploy backend + move frontend into nginx
      - name: Deploy backend and frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/AiImageDetection

            git fetch origin main
            git reset --hard origin/main
            echo "Deploying backend..."
            cd Backend
            docker compose down
            docker system prune -af
            docker builder prune -af
            docker compose up -d --build

            echo "Deploying frontend..."
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/deepcheck-frontend/dist/* /var/www/html/
            
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            sudo nginx -t
            sudo systemctl restart nginx

            docker image prune -f

            echo "Deployment complete!"